version: '3.8'

services:
  java_todolist_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_todolist_app
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_todolist_db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SECURITY_DEBUG: true
    depends_on:
      - java_todolist_db

  java_todolist_db:
    image: postgres:16
    container_name: java_todolist_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5436:5432"

  java_todolist_pgadmin:
    image: dpage/pgadmin4
    container_name: java_todolist_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8086:80"
    depends_on:
      - java_todolist_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
